--liquibase formatted sql
--changeset vemedvedev:USERS
CREATE TABLE OTPMM.USERS (
	ID INTEGER NOT NULL,
	USERTGID INTEGER NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	GENDER VARCHAR(8) NOT NULL,
	LOOKINGFOR VARCHAR(8),
	FORM_DESCRIPTION VARCHAR(255),
	FORM_TITLE VARCHAR(32),
	FORM_FILENAME VARCHAR(32),
	CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX USERS_ID_INDX ON OTPMM.USERS (ID);
CREATE UNIQUE INDEX USERS_USERTGID_INDX ON OTPMM.USERS (USERTGID);