--liquibase formatted sql
--changeset vemedvedev:USERS
CREATE TABLE NFAUT1.USERS (
	ID INTEGER NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	PASSWORD VARCHAR(64) NOT NULL,
	GENDER VARCHAR(8) NOT NULL,
	HEADER VARCHAR(32),
	LOOKINGFOR VARCHAR(8),
	DESCRIPTION VARCHAR(255),
	CREATED_AT TIMESTAMP(6) NOT NULL,
	UPDATED_AT TIMESTAMP(6) NOT NULL,
	PRIMARY KEY (ID)
);
CREATE UNIQUE INDEX USERS_ID_INDX ON NFAUT1.USERS (ID);
CREATE UNIQUE INDEX USERS_NAME_INDX ON NFAUT1.USERS (NAME);
CREATE SEQUENCE NFAUT1.USERS_S START 1;