--liquibase formatted sql
--changeset vemedvedev:USER_ATTACH
CREATE TABLE NFAUT1.USER_ATTACH (
	ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	FILE_PATH VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	CREATED_AT TIMESTAMP(6) NOT NULL,
	UPDATED_AT TIMESTAMP(6) NOT NULL,
	PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ATTACH
        FOREIGN KEY(USER_ID)
            REFERENCES NFAUT1.USERS(ID)
);
CREATE UNIQUE INDEX USER_ATTACH_ID_INDX ON NFAUT1.USER_ATTACH (ID);
CREATE UNIQUE INDEX USER_ATTACH_NAME_INDX ON NFAUT1.USER_ATTACH (USER_ID);
CREATE SEQUENCE NFAUT1.USER_ATTACH_S START 1;