--liquibase formatted sql
--changeset vemedvedev:USER_ATTACH
CREATE TABLE OTPMM.USER_ATTACH (
	ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	FILE_NAME VARCHAR(255),
	DESCRIPTION VARCHAR(255),
	CREATED_AT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
    CONSTRAINT FK_USER_ATTACH
        FOREIGN KEY(USER_ID)
            REFERENCES OTPMM.USERS(ID)
);
CREATE UNIQUE INDEX USER_ATTACH_ID_INDX ON OTPMM.USER_ATTACH (ID);
CREATE UNIQUE INDEX USER_ID_ATTACH_INDX ON OTPMM.USER_ATTACH (USER_ID);
CREATE SEQUENCE OTPMM.USER_ATTACH_S START 1;