--liquibase formatted sql
--changeset vemedvedev:USERS_LIKE
CREATE TABLE OTPMM.USERS_LIKE (
	ID INTEGER NOT NULL,
	USER_ID_WHO INTEGER NOT NULL,
	USER_ID_THAT INTEGER NOT NULL,
	CREATED_AT TIMESTAMP(6) NOT NULL,
	UPDATED_AT TIMESTAMP(6) NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_USER_WHO
	    FOREIGN KEY(USER_ID_WHO)
	        REFERENCES OTPMM.USERS(ID),
    CONSTRAINT FK_USER_THAT
        FOREIGN KEY(USER_ID_THAT)
            REFERENCES OTPMM.USERS(ID)
);
CREATE UNIQUE INDEX USERS_LIKE_ID_INDX ON OTPMM.USERS_LIKE (ID);
CREATE UNIQUE INDEX USERS_LIKE_NAME_INDX ON OTPMM.USERS_LIKE (USER_ID_WHO, USER_ID_THAT);
CREATE SEQUENCE OTPMM.USERS_LIKE_S START 1;